---
title: "Client Report - What's in a Name?"
subtitle: "Course DS 250"
author: "Jared Wightman"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import pandas as pd
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


## Project Notes

__For Project 1 the answer to each question should include a chart **and** a written response. The years labels on your charts should not include a comma. At least **two** of your charts must include reference marks.__  

```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html
# Include and execute your code here

# create base df
df = pd.read_csv("https://github.com/byuidatascience/data4names/raw/master/data-raw/names_year/names_year.csv")
```

## QUESTION|TASK 1

__How does your name at your birth year compare to its use historically?__

_The name "Jared" is found in the Bible, but did not become common until after 1965. Its usage has grown since then with a peak of 7461 in the year 1999, and has since fallen to around 1000._

```{python}
# Include and execute your code here

#df[df["name"] == "Jared"].value_counts()

jared_df = df[df["name"] == "Jared"] # new df with only info on Jared

max_year = jared_df.loc[jared_df["Total"].idxmax()] # find year of max num Jared
#print(max_year.head())
label_max = {
    'year': [max_year["year"]],
    'Total': [max_year["Total"] + 300],
    'label': [f"Peak: {int(max_year["Total"])}"]
} # dict for label position and text

(
  ggplot(jared_df, aes(x="year", y="Total")) # create plot
  + geom_line(color="darkblue") # draw data line
  + geom_vline( # draw vertical line
      xintercept=max_year["year"],
      linetype="dashed",
      color="red"
  )
  + geom_text( # draw text label for max
      data=label_max,
      mapping=aes(x="year", y="Total", label="label"),
      fill="white",
      color="red"
  )
  + labs( # set plot labels
      title="Babies born in US named Jared",
      x="Year",
      y="Num Jareds"
  )
)
```


## QUESTION|TASK 2

__If you talked to someone named Brittany on the phone, what is your guess of his or her age? What ages would you not guess?__

_I would guess that Brittany is 36, since the peak and center of the curve is the year 1990. It is possible for her to be much older or younger, but around 36 is the most likely._

```{python}
# Include and execute your code here

# refer to previous cell for functionality here

brittany_df = df[df["name"] == "Brittany"]
#brittany_df.describe()

max_year = brittany_df.loc[brittany_df["Total"].idxmax()]
#print(max_year.head())
label_max = {
    'year': [max_year["year"]],
    'Total': [max_year["Total"] + 300],
    'label': [f"Peak: {int(max_year["Total"])}"]
}

(
  ggplot(brittany_df, aes(x="year", y="Total"))
  + geom_line(color="darkblue")
  + geom_vline(
      xintercept=max_year["year"],
      linetype="dashed",
      color="red"
  )
  + geom_text(
      data=label_max,
      mapping=aes(x="year", y="Total", label="label"),
      fill="white",
      color="red"
  )
  + labs(
      title="Babies born in US named Brittany",
      x="Year",
      y="Num Brittanies"
  )
)
```


## QUESTION|TASK 3

__Mary, Martha, Peter, and Paul are all Christian names. From 1920 - 2000, compare the name usage of each of the four names in a single chart. What trends do you notice?__

_All names experience a slight dip around the time of WWII, when there were less births overall. After WWII they all increased, but have been declining since. The dips are most pronounced with the name "Mary", which has always been much more popular than the other 3._

```{python}
# Include and execute your code here

color_map = {
    "Mary": "darkblue",
    "Martha": "darkred",
    "Peter": "darkgreen",
    "Paul": "brown"
} #name-color map
names = ["Mary", "Martha", "Peter", "Paul"]
df_four = df[df["name"].isin(names)] # df containing only data on 4 names

(
    ggplot(df_four, aes(x="year", y="Total", color="name"))
    + geom_line(size=1)
    + scale_color_manual(values=color_map) # set colors of lines, based on map
    + labs(
        title="Babies born in the US",
        x="Year",
        y="Total",
        color="Name"   # legend title
    )
    + scale_x_continuous(limits=[1920, 2000]) # set custom bounds
)
```



## QUESTION|TASK 4

__Think of a unique name from a famous movie. Plot the usage of that name and see how changes line up with the movie release. Does it look like the movie had an effect on usage?__  

_A famous movie that came out in 1977 is Star Wars: A New Hope, starting a series that has since gained even more popularity. The protagonist's name, "Luke", doubled immediately after release, and has since climbed higher and higher. It seems that Star Wars has caused the name "Luke" to become more popular._

```{python}
# Include and execute your code here
movie_df = df[df["name"] == "Luke"]
total_1977 = movie_df.loc[(movie_df["year"] == 1977), "Total"].iloc[0]

label_SW = {
    'year': [1977 - 20],
    'Total': [total_1977 + 3500],
    'label': ["Release of Star Wars 4"]
}

(
  ggplot(movie_df, aes(x="year", y="Total"))
  + geom_line(color="darkblue")
  + geom_vline(
      xintercept=1977,
      linetype="dashed",
      color="brown"
  )
  + geom_text(
      data=label_SW,
      mapping=aes(x="year", y="Total", label="label"),
      fill="white",
      color="brown"
  )
  + labs(
      title="Babies born in US named Luke",
      x="Year",
      y="Total"
  )
)

```

---

## STRETCH QUESTION|TASK 1

__Reproduce the chart Elliot using the data from the `names_year.csv` file.__ 

_It appears that the usage of the name "Elliot" has gone up with each release of the popular movie "E.T," along with subsequent popularity as the name gained more traction overall._

```{python}
# Include and execute your code here

LetsPlot.setup_html(width=2000, height=600)

elliot_df = df[df["name"] == "Elliot"]

# Release Dates: 1982, 1985, 2002
label_ET = {
    'year': [1974, 1994, 2010],
    'Total': [1250, 1250, 1250],
    'label': ["E.T Released", "Second Release", "Third Release"]
} # label positions and text
color_map={"Elliot": "royalblue"}

(
  ggplot(elliot_df, aes(x="year", y="Total", color="name"))
  + geom_line(size=1.2)
  + geom_vline(
      xintercept=1982,
      linetype="dashed",
      color="red"
  )
  + geom_vline(
      xintercept=1985,
      linetype="dashed",
      color="red"
  )
  + geom_vline(
      xintercept=2002,
      linetype="dashed",
      color="red"
  )
  + geom_text(
      data=label_ET,
      mapping=aes(x="year", y="Total", label="label"),
      fill="white",
      color="black"
  )
  + theme(
      axis_title_x=element_text(family="Verdana", size=14),
      axis_title_y=element_text(family="Verdana", size=14),
      plot_title=element_text(family="Verdana", size=16),

      panel_border=element_rect(fill='white', color="white", size=2),
      panel_background=element_rect(fill='lightgray'),
      plot_background=element_rect(fill='white'),
      axis_ticks_x=element_blank(),
      axis_ticks_y=element_blank()
  )
  + labs(
      title="Elliot... What?",
      x="year",
      y="Total",
      color="name"
  )
  + scale_x_continuous(expand=(0,0), limits=[1950, 2025])
  + scale_y_continuous(expand=(0.05,0.05))
  + scale_color_manual(values=color_map)
)

```


---